name: ✨ 기능 구현 제안
description: 새로운 기능을 제안하고 요구사항을 정의합니다
title: "[기능] "
labels: ["기능 구현"]
body:
  - type: textarea
    id: background
    attributes:
      label: 배경/문제 정의
      placeholder: 왜 이 기능이 필요한가요?
    validations:
      required: true
  - type: textarea
    id: goal
    attributes:
      label: 목표/가치
      placeholder: 사용자가 얻는 이점, 성공 지표 등
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: 범위(해야 할 것 / 하지 않을 것)
      placeholder: Must / Won't
  - type: textarea
    id: requirements
    attributes:
      label: 요구사항(수용 기준)
      placeholder: |
        - [ ] 버튼 A를 누르면 B가 발생한다
        - [ ] 전원 소비 30% 감소
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: 영향 범위
      placeholder: 드라이버/펌웨어/문서/테스트 등 영향 모듈
  - type: textarea
    id: test
    attributes:
      label: 테스트/검증 계획
      placeholder: 단위/통합/하드웨어-in-the-loop 등

